version: '3'
services:
  front-end:
    image: httpd:2.4
    depends_on:
      - back-end
    links:
      - back-end:back-end
    ports:
      - "8100:80"
    volumes:
      - ./front-end/dist/:/usr/local/apache2/htdocs/
  back-end:
    build: .
    depends_on:
      - db_mysql
    links:
      - db_mysql:db_mysql
    ports:
      - "8110:80"
    volumes:
      - ./back-end:/var/www
  db_mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=dianted@root.trono238
      - MYSQL_DATABASE=db_diantetr
      - MYSQL_USER=diantetr
      - MYSQL_PASSWORD=dianted@trono238
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db_mysql
    links: 
      - db_mysql:db_mysql
    ports:
      - 8120:80
    environment:
      MYSQL_USER: diantetr
      MYSQL_PASSWORD: dianted@trono238
      MYSQL_ROOT_PASSWORD: dianted@root.trono238
      PMA_HOST: db_mysql
    restart: always